version: '3.8'

# 独立部署配置 - 使用预构建镜像
services:
  # GoComicMosaic主应用服务
  gocomicmosaic:
    # 使用Docker Hub上的官方预构建镜像
    image: 2011820123/gcm:latest
    # 容器名称
    container_name: gocomicmosaic
    # 重启策略：除非手动停止，否则总是重启
    restart: unless-stopped
    # 端口映射
    ports:
      - "80:80"     # HTTP端口
      - "443:443"   # HTTPS端口
    # 环境变量配置
    environment:
      - DOMAIN=localhost  # 应用域名，根据实际情况修改
      - TZ=Asia/Shanghai  # 时区设置
      - DB_PATH=/app/data/database.db  # 数据库文件路径
      - ASSETS_PATH=/app/data/assets  # 资源文件路径
    # 数据卷挂载
    volumes:
      # 挂载数据目录，持久化存储数据库和上传的文件
      - ./data:/app/data:rw
      # 可选：挂载SSL证书目录以支持HTTPS
      # - ./ssl:/app/data/ssl:ro
    # 健康检查配置
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s

# 网络配置
networks:
  default:
    name: gocomicmosaic-network